server:
  port: 40403
  servlet:
    context-path: /
spring:
  profiles:
    active: dev
  application:
    name: user-service
  data:
    mongodb:
      host: @spring.data.mongodb.host@
      port: @spring.data.mongodb.port@
      database: @spring.data.mongodb.database@
